_name_or_path:
    value: Qwen/Qwen2.5-1.5B-Instruct
_wandb:
    value:
        cli_version: 0.25.1
        e:
            fohgaokba3ev1u3i3xl59n17xctm2ebo:
                codePath: notebooks/03_fine_tuning.py
                codePathLocal: 03_fine_tuning.py
                cpu_count: 104
                cpu_count_logical: 208
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "21474836480"
                        used: "11186364416"
                email: samratkar77@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 2557c537cdaad5ee7a24845463fc19a271edb3c1
                    remote: https://github.com/samrat-kar/llm-fine-tune.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-8d2e37dc-4e3b-a188-e732-4e5bf16262ca
                host: a9c731e7f8eb
                memory:
                    total: "2164130975744"
                os: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
                program: /workspace/llm-fine-tune/notebooks/03_fine_tuning.py
                python: CPython 3.11.10
                root: /workspace/llm-fine-tune/notebooks
                startedAt: "2026-04-10T06:15:46.281123Z"
                writerId: fohgaokba3ev1u3i3xl59n17xctm2ebo
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 62
                - 66
            "4": 3.11.10
            "5": 0.25.1
            "6": 5.5.3
            "9":
                "1": transformers_trainer
            "12": 0.25.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_offloading:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen2ForCausalLM
assistant_only_loss:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
base_model:
    value: Qwen/Qwen2.5-1.5B-Instruct
batch_eval_metrics:
    value: false
batch_size:
    value: 16
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chat_template_path:
    value: null
chunk_size_feed_forward:
    value: 0
completion_only_loss:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_kwargs:
    value: null
dataset_num_proc:
    value: null
dataset_text_field:
    value: text
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
enable_jit_checkpoint:
    value: false
eos_token:
    value: <EOS_TOKEN>
eos_token_id:
    value: 151645
epochs:
    value: 3
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_packing:
    value: null
eval_steps:
    value: 100
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
hidden_act:
    value: silu
hidden_size:
    value: 1536
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 8960
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0002
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 25
logging_strategy:
    value: steps
lora_alpha:
    value: 32
lora_dropout:
    value: 0.05
lora_r:
    value: 16
loss_type:
    value: nll
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 1024
max_position_embeddings:
    value: 32768
max_seq_len:
    value: 512
max_steps:
    value: -1
max_window_layers:
    value: 21
metric_for_best_model:
    value: eval_loss
model/num_parameters:
    value: 1562179072
model_init_kwargs:
    value: null
model_type:
    value: qwen2
neftune_noise_alpha:
    value: null
num_attention_heads:
    value: 12
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 2
num_train_epochs:
    value: 3
optim:
    value: paged_adamw_32bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./outputs/qlora-sql
output_hidden_states:
    value: false
packing:
    value: true
packing_strategy:
    value: bfd
pad_to_multiple_of:
    value: null
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 151643
padding_free:
    value: false
parallelism_config:
    value: null
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            peft_version: 0.18.1
            qalora_group_size: 16
            r: 16
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - q_proj
                - o_proj
                - gate_proj
                - v_proj
                - up_proj
                - k_proj
                - down_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 2
per_device_train_batch_size:
    value: 2
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
quantization:
    value: 4-bit NF4
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: bfloat16
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
rms_norm_eps:
    value: 1e-06
rope_parameters:
    value:
        rope_theta: 1e+06
        rope_type: default
run_name:
    value: qwen2.5-1.5b-sql-lora-r16
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 42
shuffle_dataset:
    value: false
skip_memory_metrics:
    value: true
sliding_window:
    value: null
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_space_id:
    value: trackio
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.5.3
truncation_mode:
    value: keep_start
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.05
warmup_steps:
    value: 0.05
weight_decay:
    value: 0.01
